### ISSUE TITLE
Implementation of translations

### ISSUE THREAD

**Issue by SymWLD** [huellif/DelightApp#1]
I could make appearing "Loading ..." splashscreen message in the second language. Currently, Delight App is instructed to load a separate DelightApp_XX.qm file from C:/resource/qt/translations/ folder (and it does it correct; once the QM file is missing, Delight App shows an error on the splashscreen).

Would it be possible to make something similar with all strings in delight.cpp and all QML files? For example, test Russian translation is done for /qml/ROMPatcher.qml file. Still, the text appears only in English. So, something is definitely missing...

[DelightApp-master-with-RU-test.zip](https://github.com/huellif/DelightApp/files/4452117/DelightApp-master-with-RU-test.zip)

**Comment by huellif** [comment]
Fixed, check here:
https://github.com/huellif/DelightApp/commit/528a78cf0deb839d62cc36125d0c958af8bd3e82
