### ISSUE TITLE
Delight App v1.5.2

### ISSUE THREAD

**Issue by SymWLD** [huellif/DelightApp#2]
Hi!
GitHub does not seem to be very friendly (at least to me), I could not figure out how to pull a request successfully. Forking is not a good option either since I cannot erase old files and re-upload the updated files at once, and editing every single file here at GitHub is pointless and time-wasting...
So, it looks like Issues is the only easy way to submit something.

Please find attached the new version of Delight App.
Besides adding new files/features, I also renamed old ones to both facilitate the understanding and draw a clear line between Resolver, Selector, and Tools in QML file names.
Feel free to adapt anything you want, or just overwrite the master :)

[Delight App v1.5.2.zip](https://github.com/huellif/DelightApp/files/4911427/Delight.App.v1.5.2.zip)

**Comment by huellif** [comment]
Hello Max,

you could e.g. create a fork, delete all files, copy over yours and commit.
But don't worry, I will update this repo with your .zip, thank you!

Beste Regards,
Fabian
